---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: source-boot-seed

run:
  path: "source-boot-seed/gradlew"
  args: ["--build-file", "source-boot-seed/build.gradle", "clean", "test", "assemble"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false